# Generated by Django 4.0.2 on 2022-12-02 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('event_date', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(default='', max_length=50, verbose_name='Location')),
                ('content', models.TextField(max_length=200, verbose_name='Short description')),
                ('resumen', models.TextField(verbose_name='Detailed description')),
                ('image', models.ImageField(upload_to='eventlist/files/images')),
                ('link', models.CharField(max_length=100, verbose_name='Link')),
            ],
            options={
                'verbose_name': 'event',
                'verbose_name_plural': 'events',
                'ordering': ['event_date'],
            },
        ),
    ]
